// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aythdcrdpuoebcootlch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dGhkY3JkcHVvZWJjb290bGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTY5MDcsImV4cCI6MjA1OTY5MjkwN30.JaKmSGVzaZn8xMlbNn-3acA9Gfo3pIw63y2DtRpNYXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);